export { default as Group_1} from "./svg/Group 1.svg"
export { default as Workspace} from "./svg/Workspace.svg"
export { default as Whatsapp} from "./svg/whatsapp.svg"
export { default as Vector_9} from "./svg/Vector 9.png"
export { default as User_groups} from "./svg/User Groups.svg"
export { default as Right_arrow} from "./svg/Right Arrow.svg"
export { default as Person1} from "./svg/PERSON1.svg"
export { default as Imac2} from "./svg/iMac (2).svg"
export { default as Imac} from "./svg/iMac.svg"
export { default as Discovery} from "./svg/discovery.svg"
export { default as Development} from "./svg/development.svg"
export { default as DADC} from "./svg/DADC.svg"
export { default as Headphones} from "./svg/headphones.svg"
export { default as ContactForm} from "./svg/contact form.svg"
export { default as Whatsapp2} from "./svg/whatsapp (2).svg"
export { default as EmailUs} from "./svg/mail-02.svg"
export { default as ArrowRight} from "./svg/arrow-right-01.svg"
export { default as DAD} from "./svg/DAD.svg"
export { default as SendMessage} from "./svg/Send message.svg"
